### ISSUE TITLE
Mistakenly complaining about fps info not found

### ISSUE THREAD

**Issue by diegodlh** [Algomorph/calib_video_opencv#1]
Line 43 of offset.py makes the software complain and print the ffmpeg output if the fps is given in a format different than 00.00. For example, my videos' fps are given as 12 and 24 fps (without decimals) and thus the program complains and the output is unecessarily large.
A solution would be to change the regular expression to '(\d+(\.\d+)?)\sfps' instead.
However, if I do so, another problem arises. It happens that my videos have different fps. I don't mind about that because I'm only using the program to calculate the offset (option -coo). However, as verification of whether videos have the same fps is done in offset.py (line 216) which is run when option -coo is enabled, the program fails.
I imagine this should be verified within the run_sync function (line 57, app.py) instead, but I didn't want to try anything because I'm not familiar with this. Anyway, I couldn't find anywhere in the code where the fps are actually used.

**Comment by Algomorph** [comment]
@diegodlh,  If you'd like to add the capability to check for the different fps format (I'm not sure what's the standard there), please fork and make the corresponding PR. However, it should work for the old format as well, so the fps token should be optional, i.e. ```(:?fps)?```.

The program checks for the fps being the same since the algorithm actually assumes that they are. I'm not sure the output would look at all correct if the fps were different. It might be an easy fix, though. Again, fork & PR are welcome, as long as it doesn't break anything.

**Comment by Algomorph** [comment]
I'm going to close for now, please reopen if this is still needed.
